<a href="https://colab.research.google.com/github/ezioauditore-tech/AI/blob/main/Numpy-Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#*Numpy Basics*

##Installing and Importing Numpy

In [74]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [75]:
import numpy as np

##1. Array Creation

In [76]:
#This function creates a new array from a Python list or tuple
a=np.array([1,2,3])
a

array([1, 2, 3])

In [77]:
#This function creates a new array filled with zeros of a specified shape
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
#This function creates a new array filled with ones of a specified shape
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
#This function creates a new array filled with a specified value of a specified shape
a=np.full((2,3),5)
a

array([[5, 5, 5],
       [5, 5, 5]])

In [80]:
#This function creates a new identity matrix of a specified size
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
#This function creates a new array filled with random values between 0 and 1 of a specified shape
a=np.random.rand(2,3)
a

array([[0.00940319, 0.52385387, 0.76248279],
       [0.07038177, 0.73549119, 0.43241331]])

##2. Array Manipulation

In [82]:
#This function returns a new array with a specified shape
a=np.array([[1,2,3],[4,5,6]])
a=np.reshape(a,(3,2))
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [83]:
#This function returns a new array with the dimensions transposed
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=np.transpose(a)
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [84]:
#This function joins two or more arrays along a specified axis-The axis parameter is used to specify along which dimension(s) a particular operation should be performed
#When axis=0, the operation is performed along the rows of a two-dimensional array
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
c=np.concatenate((a,b),axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
#This function splits an array into multiple sub-arrays
a=np.array([1,2,3,4,5,6])
a=np.split(a,3)
a

[array([1, 2]), array([3, 4]), array([5, 6])]

In [86]:
#This function stacks arrays vertically
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
c=np.vstack((a,b))
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
#This function stacks arrays horizontally
b=b.T
c=np.hstack((a,b))
c

array([[1, 2, 5],
       [3, 4, 6]])

##3. Mathematical Functions

In [88]:
#This function adds two arrays element-wise
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.add(a,b)
c

array([5, 7, 9])

In [89]:
#This function subtracts two arrays element-wise
c=np.subtract(a,b)
c

array([-3, -3, -3])

In [90]:
#This function multiplies two arrays element-wise
c=np.multiply(a,b)
c

array([ 4, 10, 18])

In [91]:
#This function divides two arrays element-wise
c=np.divide(a,b)
c

array([0.25, 0.4 , 0.5 ])

In [92]:
#This function raises each element of an array to a specified power
a=np.array([1,2,3])
a=np.power(a,3)
a

array([ 1,  8, 27])

In [93]:
#This function returns the exponential of each element in an array
a=np.array([1,2,3])
a=np.exp(a)
a

array([ 2.71828183,  7.3890561 , 20.08553692])

In [94]:
#This function computes the absolute value of each element in the array
a=np.array([-1,-2,-3,-4])
a=np.abs(a)
a

array([1, 2, 3, 4])

In [95]:
#This function computes the square root of each element in the array
a=np.array([4,9,16])
a=np.sqrt(a)
a


array([2., 3., 4.])

##4. Statistical Functions

In [96]:
#This function computes the arithmetic mean along a specified axis
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.mean(a,axis=0)
b

array([4., 5., 6.])

In [97]:
#This function computes the median along a specified axis
a=np.array([[2,3,4],[1,4,7],[3,5,6]])
b=np.median(a,axis=0)
b

array([2., 4., 6.])

In [98]:
#This function computes the variance along a specified axis
b=np.var(a,axis=0)
b

array([0.66666667, 0.66666667, 1.55555556])

In [99]:
#This function computes the standard deviation along a specified axis
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.std(a,axis=0)
b

array([2.44948974, 2.44948974, 2.44948974])

In [100]:
#This function returns the minimum value along a specified axis
b=np.min(a,axis=0)
b

array([1, 2, 3])

In [101]:
#This function returns the maximum value along a specified axis
b=np.max(a,axis=0)
b

array([7, 8, 9])

In [102]:
#This function computes the covariance matrix of a given array
b=np.cov(a)
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
#This function computes the correlation matrix of a given array
b=np.corrcoef(a)
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [104]:
#This function computes the q-th percentile of a given array along a specified axis
b=np.percentile(a,50,axis=0)
b

array([4., 5., 6.])

##5. Linear algebra 

In [105]:
#This function computes the dot product of two arrays. For 2-D arrays it is equivalent to matrix multiplication
a=np.array([[1,2],[4,5]])
b=np.array([[7,8],[10,11]])
c=np.dot(a,b)
c

array([[27, 30],
       [78, 87]])

In [106]:
#This function computes the trace of a given array. The trace of a square matrix is the sum of its diagonal elements
a=np.array([[1,3],[1,7]])
b=np.trace(a)
b

8

In [107]:
#This function computes the inverse of a given matrix
b=np.linalg.inv(a)
b

array([[ 1.75, -0.75],
       [-0.25,  0.25]])

In [108]:
#This function computes the determinant of a given matrix
b=np.linalg.det(a)
b

4.0

In [109]:
#This function computes the eigenvalues and eigenvectors of a given square matrix
eigval,eigvec=np.linalg.eig(a)
print("Eigenvalues: ",eigval)
print("Eigenvectors: ",eigvec)

Eigenvalues:  [0.53589838 7.46410162]
Eigenvectors:  [[-0.98824446 -0.42097392]
 [ 0.15288195 -0.90707274]]


In [110]:
#This function computes the singular value decomposition (SVD) of a given matrix
a=np.array([[1,2],[3,4],[5,6]])
u,s,v=np.linalg.svd(a)
print('U: ',u)
print('S: ',s)
print('V: ',v)

U:  [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S:  [9.52551809 0.51430058]
V:  [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


##6. Trigonometric functions

In [111]:
#This function returns the sine of a given angle in radians
a=np.pi/2
b=np.sin(a)
b

1.0

In [112]:
#This function returns the cosine of a given angle in radians
a=np.pi/3
b=np.cos(a)
b

0.5000000000000001

In [113]:
#This function returns the tangent of a given angle in radians
a=np.pi/4
b=np.tan(a)
b

0.9999999999999999

In [114]:
#This function returns the inverse sine (or arcsine) of a given value
a=1
b=np.arcsin(a)
b

1.5707963267948966

In [115]:
#This function returns the inverse cosine (or arccosine) of a given value
a=0.5
b=np.arccos(a)
b

1.0471975511965979

In [116]:
#This function returns the inverse tangent (or arctangent) of a given value
a=0.99
b=np.arctan(a)
b

0.7803730800666359

In [117]:
#This function converts a given angle from degrees to radians
a=180
b=np.deg2rad(a)
b

3.141592653589793

In [118]:
#This function converts a given angle from radians to degrees
a=np.pi/4
b=np.rad2deg(a)
b

45.0

In [119]:
#This function returns the Euclidean distance (or hypotenuse) between two points
a=3
b=4
c=np.hypot(a,b)
c

5.0

##7. Random number generation functions

In [120]:
#This function returns an array of random numbers between 0 and 1 with the given shape
a=np.random.rand(3,2)
a

array([[0.01051965, 0.49847565],
       [0.86657348, 0.48814771],
       [0.83163159, 0.64707545]])

In [121]:
#This function returns an array of random numbers from a normal distribution with the given shape
a=np.random.randn(3,2)
a

array([[ 0.83326661, -1.85752986],
       [-0.95313069,  0.84658453],
       [-0.01450855, -0.45586195]])

In [122]:
#This function returns an array of random integers between the given range with the given shape
a=np.random.randint(0,10,(3,2))
a

array([[1, 6],
       [2, 7],
       [2, 0]])

In [123]:
#This function returns an array of random values chosen from a given array with the given shape
a=np.random.choice(['apple','banana','orange'],size=(3,3))
a

array([['apple', 'orange', 'banana'],
       ['apple', 'banana', 'banana'],
       ['banana', 'apple', 'banana']], dtype='<U6')

In [124]:
#This function returns an array of random numbers from a normal distribution with the given mean and standard deviation
a=np.random.normal(0,2,(3,3))
a

array([[-1.05910791,  0.69233004,  0.47110572],
       [ 2.06989214,  2.0349981 ,  2.5125619 ],
       [-1.51963145,  1.3860772 , -3.17153868]])

In [125]:
#This function returns an array of random numbers between the given range with the given shape
a=np.random.uniform(1,2,(3,3))
a

array([[1.40281474, 1.27370002, 1.34604123],
       [1.26554461, 1.28947917, 1.78396163],
       [1.08149938, 1.59071569, 1.48561664]])

In [126]:
#This function returns a shuffled sequence of a given array
a=np.random.permutation([1,2,3,4,5])
a

array([5, 3, 4, 2, 1])

In [127]:
 #This function shuffles a given array in place
 a=np.array([1,2,3,4,5])
 np.random.shuffle(a)
 a

array([3, 1, 5, 4, 2])