<a href="https://colab.research.google.com/github/ezioauditore-tech/AI/blob/main/Neural-Network-From-Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#*NEURAL NETWORK FROM SCRATCH*

In [41]:
import numpy as np


##Create X and Y 

In [42]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [43]:
y=np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

## Create A Sigmoid Function

In [44]:
def sigmoid(x):
  return 1/(1+np.exp(-x))
  

In [45]:
def derivative_sigmoid(x):
  return x*(1-x)


##Intitalize The Variables

In [46]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1


##Intialize Weights and Bias

In [47]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))


## Training the model

In [48]:
for i in range(epoch):
  #forward
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)
  #backward
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr
  

In [49]:
output

array([[0.95093656],
       [0.06572448],
       [0.96494974]])